//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Data.LocationDashboard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using A8Dashboard.Models.LocationDashboard;
    public partial class LocationDbAprilEntities : DbContext
    {
        public LocationDbAprilEntities()
            : base("name=LocationDbAprilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CruisedDiscovery> CruisedDiscoveries { get; set; }
        public virtual DbSet<Data_1701> Data_1701 { get; set; }
        public virtual DbSet<Data_1703> Data_1703 { get; set; }
        public virtual DbSet<DataFile> DataFiles { get; set; }
        public virtual DbSet<InterestLocation> InterestLocations { get; set; }
        public virtual DbSet<LocationIndicator> LocationIndicators { get; set; }
        public virtual DbSet<NeighBourArea> NeighBourAreas { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
    }
}
