//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using A8DashBoard.Models.A8Product;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace A8Dashboard.Models.CustomUserIdentity
{
    using A8Product;
    using CustomUserIdentity;
    using System;
    using System.Collections.Generic;
    using System.Security.Claims;
    using System.Threading.Tasks;

    public partial class User : IdentityUser<int, UserLogin, UserRole, UserClaim>, IUser<int>
    {

        public async Task<ClaimsIdentity>
           GenerateUserIdentityAsync(UserManager<User, int> manager)
        {
            var userIdentity = await manager
                .CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            return userIdentity;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AdminSiteAccesses = new HashSet<AdminSiteAccess>();
            this.ApiAccessUserSessions = new HashSet<ApiAccessUserSession>();
            this.MacAddresses = new HashSet<MacAddress>();
            this.UserClaims = new HashSet<UserClaim>();
            this.UserLogins = new HashSet<UserLogin>();
            this.UsersAddresses = new HashSet<UsersAddress>();
            this.Roles = new HashSet<Role>();
        }
    
        public override int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> MobileNumer { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> AgeId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<bool> promotional_email { get; set; }
        public Nullable<bool> ThirdPartyOptIn { get; set; }
        public Nullable<bool> UserOfDataOptIn { get; set; }
        public string Status { get; set; }
        public override string Email { get; set; }
        public override bool  EmailConfirmed { get; set; }
        public override string PasswordHash { get; set; }
        public override string SecurityStamp { get; set; }
        public override string PhoneNumber { get; set; }
        public override bool PhoneNumberConfirmed { get; set; }
        public override bool TwoFactorEnabled { get; set; }
        public override Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public override bool LockoutEnabled { get; set; }
        public override int AccessFailedCount { get; set; }
        public override string UserName { get; set; }
        public Nullable<bool> AutoLogin { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Custom6 { get; set; }
        public string UniqueUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminSiteAccess> AdminSiteAccesses { get; set; }
        public virtual Age Age { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiAccessUserSession> ApiAccessUserSessions { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MacAddress> MacAddresses { get; set; }
        public virtual Site Site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserClaim> UserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersAddress> UsersAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public new ICollection<Role> Roles { get; set; }
    }
}
