//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Models.A8Product
{
    using System;
    using System.Collections.Generic;
    using CustomUserIdentity;
    public partial class ApiAccessUserSession
    {
        public int UserSessionId { get; set; }
        public int UserId { get; set; }
        public string SessionId { get; set; }
    
        public virtual User User { get; set; }
    }
}
