//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Models.A8Product
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormControl
    {
        public int FormControlId { get; set; }
        public int FormId { get; set; }
        public string LabelName { get; set; }
        public string LabelNameToDisplay { get; set; }
        public bool IsMandetory { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
