//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Models.A8Product
{
    using CustomUserIdentity;
    using System;
    using System.Collections.Generic;

    public partial class MacAddress
    {
        public int MacId { get; set; }
        public string MacAddressValue { get; set; }
        public int UserId { get; set; }
        public string BrowserName { get; set; }
        public string OperatingSystem { get; set; }
        public bool IsMobile { get; set; }
        public string UserAgentName { get; set; }
        public bool IsRegisterInRtls { get; set; }
    
        public virtual User User { get; set; }
    }
}
