//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Models.A8Product
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagePromotion
    {
        public int ManagePromotionId { get; set; }
        public int SiteId { get; set; }
        public string SuccessPageOption { get; set; }
        public string WebPageURL { get; set; }
        public string OptionalPictureForSuccessPage { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
