//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Models.A8Product
{
    using CustomUserIdentity;
    using System;
    using System.Collections.Generic;

    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.Forms = new HashSet<Form>();
            this.ManagePromotions = new HashSet<ManagePromotion>();
            this.Users = new HashSet<User>();
        }
    
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> AutoLogin { get; set; }
        public string ControllerIpAddress { get; set; }
        public string MySqlIpAddress { get; set; }
        public string Term_conditions { get; set; }
        public string TermsAndCondDoc { get; set; }
        public string RtlsUrl { get; set; }
        public string DashboardUrl { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form> Forms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagePromotion> ManagePromotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
