//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8DashBoard.Data.A8Product
{
    using System.Data.Entity;
    public partial class A8ProdcutEntities : DbContext
    {
     
    }
}
