//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8DashBoard.Data.A8Product
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using A8Dashboard.Models.CustomUserIdentity;
    using A8Dashboard.Models.A8Product;

    public partial class A8ProdcutEntities : DbContext
    {
        public A8ProdcutEntities()
            : base("name=A8ProdcutEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AdminSiteAccess> AdminSiteAccesses { get; set; }
        public virtual DbSet<Age> Ages { get; set; }
        public virtual DbSet<ApiAccessUserSession> ApiAccessUserSessions { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<FormControl> FormControls { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<MacAddress> MacAddresses { get; set; }
        public virtual DbSet<ManagePromotion> ManagePromotions { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersAddress> UsersAddresses { get; set; }
    }
}
