//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Models.LocationDashboard
{
    using System;
    
    public partial class CruisedDiscovery
    {
        public int Id { get; set; }
        public string Day { get; set; }
        public System.DateTime Date { get; set; }
        public string CruiseName { get; set; }
        public string TUIDiscovery { get; set; }
        public string Arrival { get; set; }
        public string Departure { get; set; }
        public Nullable<int> TimeDiff { get; set; }
    }
}
