//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Models.LocationDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_1703
    {
        public string MacAddress { get; set; }
        public string AreaId { get; set; }
        public Nullable<System.DateTime> myDate { get; set; }
        public Nullable<System.TimeSpan> myTime { get; set; }
        public Nullable<System.DateTime> myDateTime { get; set; }
        public string Y { get; set; }
        public string X { get; set; }
        public int Id { get; set; }
    }
}
