//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Models.LocationDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationIndicator
    {
        public int LoctionIndicatorId { get; set; }
        public int AreaOfInterestId { get; set; }
        public string LoctionIndicator { get; set; }
    
        public virtual InterestLocation InterestLocation { get; set; }
    }
}
