//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8Dashboard.Models.LocationDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeighBourArea
    {
        public int NeighbourAreaId { get; set; }
        public string AreaCode { get; set; }
        public int AreaId { get; set; }
    
        public virtual InterestLocation InterestLocation { get; set; }
    }
}
